import { getDb } from "@/lib/db";
import { NextResponse } from "next/server";

// Export generation API — creates deployment plans, QBRs, health snapshots
export async function POST(request: Request) {
  try {
    const { customerId, type, kickoffDate }: 
      { customerId: string; type: "deployment" | "qbr" | "health" | "value"; kickoffDate?: string } = await request.json();

    if (!customerId || !type) {
      return NextResponse.json({ error: "customerId and type required" }, { status: 400 });
    }

    const db = getDb();
    const customer = db.prepare("SELECT * FROM customers WHERE id = ?").get(customerId) as Record<string, unknown> | undefined;
    if (!customer) {
      return NextResponse.json({ error: "Customer not found" }, { status: 404 });
    }

    const contacts = db.prepare("SELECT * FROM contacts WHERE customer_id = ?").all(customerId);
    const openItems = db.prepare("SELECT * FROM open_items WHERE customer_id = ? AND status = ?").all(customerId, "Pending");
    const calls = db.prepare("SELECT * FROM call_history WHERE customer_id = ? ORDER BY date DESC").all(customerId);
    const insights = db.prepare("SELECT * FROM insights WHERE customer_id = ? ORDER BY date DESC").all(customerId);

    let content = "";
    let filename = "";

    switch (type) {
      case "deployment":
        content = generateDeploymentPlan(customer, contacts, openItems, kickoffDate);
        filename = `Deployment_Plan_${customer.name}_${new Date().toISOString().split("T")[0]}.md`;
        break;
      case "qbr":
        content = generateQBR(customer, contacts, openItems, calls, insights);
        filename = `QBR_${customer.name}_${new Date().toISOString().split("T")[0]}.md`;
        break;
      case "health":
        content = generateHealthSnapshot(customer, contacts, openItems, insights);
        filename = `Health_Snapshot_${customer.name}_${new Date().toISOString().split("T")[0]}.md`;
        break;
      case "value":
        content = generateValueProp(customer, contacts, insights);
        filename = `Value_Prop_${customer.name}_${new Date().toISOString().split("T")[0]}.md`;
        break;
    }

    return NextResponse.json({
      content,
      filename,
      type,
      customerName: customer.name,
    });
  } catch (error) {
    console.error("POST /api/export error:", error);
    return NextResponse.json({ error: "Failed to generate export" }, { status: 500 });
  }
}

function generateDeploymentPlan(customer: Record<string, unknown>, contacts: unknown[], openItems: unknown[], kickoffDate?: string) {
  const primaryContact = (contacts as Record<string, unknown>[])[0] || {};
  const items = (openItems as Record<string, unknown>[]).map((i) => `- ${i.item} (Owner: ${i.owner || "TBD"})`).join("\n") || "No open items.";

  return `# Deployment Plan — ${customer.name}

**Account Manager:** ${customer.account_manager || "Jeffrey Calabro"}  
**Kickoff Date:** ${kickoffDate || new Date().toISOString().split("T")[0]}  
**Account Type:** ${customer.account_type || "Standard"}  
**Generated:** ${new Date().toLocaleDateString()}

---

## Primary Contact

${primaryContact.name || "TBD"} ${primaryContact.title ? `— ${primaryContact.title}` : ""}  
${primaryContact.email || ""} ${primaryContact.phone ? `| ${primaryContact.phone}` : ""}

## Success Criteria

${customer.success_criteria || "TBD — to be defined with customer."}

## Open Items

${items}

## Watch-Outs

- All devices must be added to account BEFORE shipping
- Monitor first 3 shipments closely after go-live
- Validate geofence radius and trigger accuracy

## Next Steps

1. Confirm origin facility list and addresses
2. Configure alert thresholds in Honeycomb
3. Schedule go-live validation call

---
*Generated by Decklar AI Intelligence System*
`;
}

function generateQBR(customer: Record<string, unknown>, contacts: unknown[], openItems: unknown[], calls: unknown[], insights: unknown[]) {
  const recentCalls = (calls as Record<string, unknown>[]).slice(0, 3);
  const recentInsights = (insights as Record<string, unknown>[]).slice(0, 3);
  const pendingItems = (openItems as Record<string, unknown>[]).filter((i) => i.status === "Pending");

  return `# Quarterly Business Review — ${customer.name}

**Date:** ${new Date().toLocaleDateString()}  
**Account Manager:** ${customer.account_manager || "Jeffrey Calabro"}  
**Health Status:** ${customer.health_rag?.toUpperCase() || "GREEN"}

---

## Executive Summary

${customer.name} is a ${customer.account_type || "Standard"} account managed by ${customer.account_manager || "Jeffrey Calabro"}. 
Last contact: ${customer.last_contact ? new Date(customer.last_contact as string).toLocaleDateString() : "N/A"}.

## Deployment Status

${customer.status === "active" ? "✅ Active" : "⏳ Not yet live"}

## Recent Activity

${recentCalls.map((c) => `- ${new Date(c.date as string).toLocaleDateString()}: ${c.type || "Call"} — ${c.summary ? (c.summary as string).substring(0, 100) + "..." : "No summary"}`).join("\n") || "No recent calls."}

## Open Items

${pendingItems.length > 0 ? pendingItems.map((i) => `- **${i.item}** (Owner: ${i.owner || "TBD"}, Due: ${i.due_date ? new Date(i.due_date as string).toLocaleDateString() : "TBD"})`).join("\n") : "No pending items."}

## Insights & Risks

${recentInsights.map((i) => `- [${(i.type || "note").toUpperCase()}] ${i.text}`).join("\n") || "No insights recorded."}

## Recommended Next Steps

1. Review open items and confirm ownership
2. Schedule next check-in call
3. Validate go-live timeline

---
*Generated by Decklar AI Intelligence System*
`;
}

function generateHealthSnapshot(customer: Record<string, unknown>, contacts: unknown[], openItems: unknown[], insights: unknown[]) {
  const health = (customer.health_rag || "green").toLowerCase();
  const healthEmoji = health === "red" ? "🔴" : health === "amber" ? "🟡" : "🟢";
  const pendingItems = (openItems as Record<string, unknown>[]).slice(0, 3);
  const risks = (insights as Record<string, unknown>[]).filter((i) => ["warning", "risk"].includes(i.type as string)).slice(0, 2);

  return `# Account Health Snapshot — ${customer.name}

${healthEmoji} **${health.toUpperCase()}**  
**Last Contact:** ${customer.last_contact ? new Date(customer.last_contact as string).toLocaleDateString() : "N/A"}  
**Generated:** ${new Date().toLocaleDateString()}

---

## Top Open Items

${pendingItems.length > 0 ? pendingItems.map((i) => `${i.due_date && new Date(i.due_date as string) < new Date() ? "🔴 OVERDUE" : "⏳"} ${i.item} (Owner: ${i.owner || "TBD"})`).join("\n") : "✅ No pending items."}

## Key Risks

${risks.length > 0 ? risks.map((r) => `⚠️ ${r.text}`).join("\n") : "✅ No risks flagged."}

## Recommended Action This Week

${pendingItems.length > 0 ? `Follow up on: ${pendingItems[0].item}` : "Schedule routine check-in call."}

---
*Generated by Decklar AI Intelligence System*
`;
}

function generateValueProp(customer: Record<string, unknown>, contacts: unknown[], insights: unknown[]) {
  const opportunities = (insights as Record<string, unknown>[]).filter((i) => i.type === "opportunity").slice(0, 3);

  return `# Value Proposition — ${customer.name}

**Prepared for:** ${customer.account_manager || "Jeffrey Calabro"}  
**Date:** ${new Date().toLocaleDateString()}  
**Account Type:** ${customer.account_type || "Standard"}

---

## Why Decklar Works for ${customer.name}

${customer.success_criteria ? `Success criteria: "${customer.success_criteria}"` : "Customer success criteria to be defined."}

## Expansion Opportunities

${opportunities.length > 0 ? opportunities.map((o) => `- 💡 ${o.text}`).join("\n") : "No expansion opportunities recorded yet."}

## Recommended Next Step

Schedule a business review call to discuss growth and expanded usage.

---
*Generated by Decklar AI Intelligence System*
`;
}
